module.exports = {
    L01: 'ARQUITECTURA',
    L02: 'INGENIERÍA CIVIL',
    L03: 'INGENIERÍA ELÉCTRICA',
    L04: 'INGENIERÍA INDUSTRIAL',
    L05: 'INGENIERÍA EN SISTEMAS COMPUTACIONALES',
    L06: 'INGENIERÍA BIOQUÍMICA',
    L07: 'INGENIERÍA QUÍMICA',
    L08: 'LICENCIATURA EN ADMINISTRACIÓN',
    L11: 'INGENIERÍA MECATRÓNICA',
    L12: 'INGENIERÍA EN GESTIÓN EMPRESARIAL',
    ITI: 'INGENIERÍA EN TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIONES',
    MTI: 'MAESTRÍA EN TECNOLOGÍAS DE LA INFORMACIÓN',
    P01: 'MAESTRÍA EN CIENCIAS EN ALIMENTOS',
    DCA: 'DOCTORADO EN CIENCIAS EN ALIMENTOS'
};