const eFILES={
    CURP:"CURP",
    PROYECTO:"PROYECTO",
    ACTA_NACIMIENTO:"ACTA_NACIMIENTO"
}

const eCAREER={
    ARQUITECTURA:"ARQUITECTURA",
    INGENIERIA_CIVIL:"INGENIERÍA CIVIL",
    INGENIERIA_ELECTRICA:"INGENIERÍA ELÉCTRICA",
    INGENIERIA_INDUSTRIAL:"INGENIERÍA INDUSTRIAL",
    INGENIERIA_EN_SISTEMAS_COMPUTACIONALES:"INGENIERÍA EN SISTEMAS COMPUTACIONALES",
    INGENIERIA_BIOQUIMICA:"INGENIERÍA BIOQUÍMICA",
    INGENIERIA_QUIMICA:"INGENIERÍA QUÍMICA",
    LICENCIATURA_EN_ADMINISTRACION:"LICENCIATURA EN ADMINISTRACIÓN",
    INGENIERIA_EN_GESTION_EMPRESARIAL:"INGENIERÍA EN GESTIÓN EMPRESARIAL",
    INGENIERIA_MECATRONICA:"INGENIERÍA MECATRÓNICA",
    INGENIERIA_EN_TECNOLOGIAS_DE_LA_INFORMACION_Y_COMUNICACIONES:"INGENIERÍA EN TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIONES",
    MAESTRIA_EN_TECNOLOGIAS_DE_LA_INFORMACION:"MAESTRIA EN TECNOLOGÍAS DE LA INFORMACIÓN",
    MAESTRIA_EN_CIENCIAS_DE_ALIMENTOS:"MAESTRIA EN CIENCIAS DE ALIMENTOS",
    DOCTORADO_EN_CIENCIAS_DE_ALIMENTOS:"DOCTORADO EN CIENCIAS DE ALIMENTOS"
}


module.exports=eFILES;
module.exports=eCAREER;

